FROM node:22-alpine 

WORKDIR /app

RUN corepack enable  

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3333

CMD [ "pnpm" , "start:dev" ]
