version: '3.9'

services:
  app: 
    container_name: backend_projeto_extensao_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - 3333:3333
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: bitnami/postgresql:latest
    container_name: db-projeto-extensao-production
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: db_projeto_extensao_prod
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
