FROM node:22-alpine 

WORKDIR /app

RUN npm install -g corepack@0.31.0 && \
    corepack enable && \
    corepack prepare pnpm@10.12.1 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

EXPOSE 3333

CMD [ "pnpm" , "start:dev" ]
