version: '3.9'

services:
  app: 
    container_name: backend_projeto_extensao_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - 3333:3333
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: bitnami/postgresql:latest
    container_name: db-projeto-extensao-production
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    env_file:
      - .env.production
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
