volumes:
  postgres_data:
  redis_data:

services:
  postgresql:
    container_name: db-projeto-extensao
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgres/test-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: cache-projeto-extensao
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  toxiproxy:
    container_name: toxiproxy
    image: ghcr.io/shopify/toxiproxy
    ports:
      - "8474:8474"
      - "13333:13333" # porta do proxy
