import type { DOCUMENT_TYPE, ROLE } from '@/shared/types';
import {
  generateBirthDate,
  generateUniqueCPF,
  generateEmail,
  generateName,
  generateUUID,
} from '../generate-data';

export const users = [
  {
    id: generateUUID(),
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: generateName(),
    email: generateEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
