import type { DOCUMENT_TYPE, ROLE } from '@/shared/types';
import {
  generateBirthDate,
  generateUniqueCPF,
  generateUniqueEmail,
  generateUniqueName,
} from '../generate-data';
import { generateUUID } from '../generate-uuid';

export const users = [
  {
    id: generateUUID(),
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateUUID(),
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: generateBirthDate(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: generateUniqueName(),
    email: generateUniqueEmail(),
    role: 'PATIENT' as ROLE,
    document: generateUniqueCPF(),
    documentType: 'CPF' as DOCUMENT_TYPE,
    birthDate: new Date('1994-05-05'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
