FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . ./

EXPOSE 3333
EXPOSE 5555

ENV NODE_ENV=development

CMD [ "pnpm", "start:dev" ]

