name: backend_projeto_de_extensao

volumes:
  postgres_data:
  redis_data:

services:
  # TODO => criar service para usar Dockerfile corretamente para dev
  postgresql:
    container_name: db-projeto-extensao
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: db_projeto_extensao
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgres:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_projeto_extensao"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: cache-projeto-extensao
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  toxiproxy:
    container_name: toxiproxy
    image: ghcr.io/shopify/toxiproxy
    ports:
      - "8474:8474"
      - "13333:13333" # porta do proxy
    restart: unless-stopped
