name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    run-e2e-tests:
      name: Run E2E Tests
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma:generate

      - name: Start E2E Database
        run: docker compose up -d postgresql-e2e
      - name: Wait For E2E Database
        run: |
          apt-get update && apt-get install -y wait-for-it
          wait-for-it localhost:5434 --timeout=60

      - run: pnpm test:coverage:e2e
