name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    run-e2e-tests:
      name: Run E2E Tests
      runs-on: ubuntu-latest

      services:
        postgresql-e2e:
          image: bitnami/postgresql:latest
          ports:
            - 5432:5432
          env:
              POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME_TEST_E2E }}
              POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD_TEST_E2E }}
              POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE_TEST_E2E }}
       
      env:
        DATABASE_URL: postgresql://${{ secrets.POSTGRESQL_USERNAME_TEST_E2E }}:${{ secrets.POSTGRESQL_PASSWORD_TEST_E2E }}@localhost:5432/${{ secrets.POSTGRESQL_DATABASE_TEST_E2E }}
        CORS_ORIGIN: http://localhost:5173
   

      steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma:generate
      - name: Wait For E2E Database
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && echo "DB is up!" && break
            echo "Waiting for DB..."
            sleep 1
          done
      - run: pnpm test:coverage:e2e
