name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgresql-test:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        volumes:
          - postgres_data_test:/bitnami/postgresql
        env:
          POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME_TEST }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD_TEST }}
          POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE_TEST }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma:generate
      - name: Create .env.test
        run: |
          echo "POSTGRESQL_USERNAME=${{ secrets.POSTGRESQL_USERNAME_TEST }}" > .env.test
          echo "POSTGRESQL_PASSWORD=${{ secrets.POSTGRESQL_PASSWORD_TEST }}" >> .env.test
          echo "POSTGRESQL_PORT=5433" >> .env.test
          echo "POSTGRESQL_DATABASE=${{ secrets.POSTGRESQL_DATABASE_TEST }}" >> .env.test
          echo "DATABASE_URL=\"postgresql://${{ secrets.POSTGRESQL_USERNAME_TEST }}:${{ secrets.POSTGRESQL_PASSWORD_TEST }}@localhost:5433/${{ secrets.POSTGRESQL_DATABASE_TEST }}?schema=public\"" >> .env.test
      - name: Wait For Test Database
        run: |
          for i in {1..30}; do
            nc -z localhost 5433 && echo "DB is up!" && break
            echo "Waiting for DB..."
            sleep 1
          done
      - run: pnpm test:coverage
